
export const AnimationComponents = [
  {
    name: "anim videl flying kick",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 8,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim crono cyclone",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim crono slash",
    repeatInterval: 8,
    startTick: 0,
    endTick: 23,
    animationSpeed: 0,
    animationIndex: 2,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim crono cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim frog cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim robo tackle",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 6,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim saitama leap slam",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 1.0,
    animationIndex: 4,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim saitama serious punch",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 7,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  // {
  //   name: "anim dk roll",
  //   repeatInterval: 2,
  //   startTick: 0,
  //   endTick: -1,
  //   animationSpeed: 0,
  //   animationIndex: 7,
  //   animationString: "",
  //   addAnimationProperty: "",
  //   onlyApplyAtStart: false,
  //   resetAnimation: true,
  // },
  {
    name: "anim dk jungle rush",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 11,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim hirudegarn chou fire",
    repeatInterval: 33,
    startTick: 33,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "throw",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim sonic jump",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 11,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim waluigi spin",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim goku black spin",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 11,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim peco royal slash",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 6,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim peco princess strike",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 17,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim peco princess valiant",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 4,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim demiurge giant arm",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 16,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim demiurge jaldabaoth",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim might guy dynamic entry",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 15,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim might guy leaf hurricane",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim might guy yagai",
    repeatInterval: 1,
    startTick: 101,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 15,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
];