import { AOEHeal } from "CustomAbility/AbilityComponent/AOEHeal";
import { BASE_DMG } from "Common/Constants";

export const AOEHealComponents = [
  {
    name: "heal caster bankai hollow",
    repeatInterval: 5,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_AGI,
    maxHealthHealPercent: 0.006,
    requireBuff: false,
    buffId: 0,
  },
  // frog slurp
  {
    name: "heal frog slurp",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 300,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: 3,
    healMult: BASE_DMG.KAME_DPS * 2,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.0,
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "heal frog slurp bonus",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 300,
    maxHealTargets: 1,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: false,
    maxHealTicks: 1,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.04,
    requireBuff: false,
    buffId: 0,
  },
  // robo heal beam
  {
    name: "heal robo heal beam",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 800,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: 40,
    healMult: BASE_DMG.KAME_DPS * 0.18,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.0005,
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "heal marle aura",
    repeatInterval: 11,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 800,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: 15,
    healMult: BASE_DMG.KAME_DPS * 0.11,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.008,
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "heal marle cure",
    repeatInterval: 1,
    startTick: 66,
    endTick: 66,
    healSource: AOEHeal.SOURCE_TARGET_POINT_FIXED,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: true,
    aoe: 600,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: BASE_DMG.KAME_DPS * 20,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.02,
    requireBuff: false,
    buffId: 0,
  },
  // hirudegarn tail attack
  {
    name: "heal hirudegarn tail attack",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: BASE_DMG.KAME_DPS * 0.03,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.00025,
    requireBuff: false,
    buffId: 0,
  },
  // hirudegarn molting
  {
    name: "heal hirudegarn molting",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: BASE_DMG.KAME_DPS * 0.12,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.00006,
    requireBuff: false,
    buffId: 0,
  },
  // schala magic orbs
  {
    name: "heal schala magic orbs",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 900,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: BASE_DMG.KAME_DPS * 0.5,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.005,
    requireBuff: false,
    buffId: 0,
  },
  // rust gobble
  {
    name: "heal caster rust gobble",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_STR,
    maxHealthHealPercent: 0.1,
    requireBuff: false,
    buffId: 0,
  },
  // peco onigiri time
  {
    name: "heal peco onigiri time",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_STR,
    maxHealthHealPercent: 0.0015,
    requireBuff: false,
    buffId: 0,
  },
  // peco princess force
  {
    name: "heal peco princess force",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 800,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: 1,
    healMult: BASE_DMG.KAME_DPS * 150,
    healAttribute: bj_HEROSTAT_STR,
    maxHealthHealPercent: 0.05,
    requireBuff: false,
    buffId: 0,
  },
  // dende guardian devotion
  {
    name: "heal dende guardian devotion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1200,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: false,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_INT,
    maxHealthHealPercent: 0.00033,
    requireBuff: false,
    buffId: 0,
  },
  // item cell max wings
  {
    name: "heal item cell max wings",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    healSource: AOEHeal.SOURCE_UNIT,
    sourceHPHealScale: 0,
    useInverseHealScale: true,
    useLastCastPoint: false,
    aoe: 1,
    maxHealTargets: AOEHeal.UNLIMITED_HEAL_TARGETS,
    onlyHealHeroes: true,
    onlyHealCaster: true,
    canHealCaster: true,
    maxHealTicks: AOEHeal.UNLIMITED_HEAL_TICKS,
    healMult: 0.0,
    healAttribute: bj_HEROSTAT_STR,
    maxHealthHealPercent: 0.0003,
    requireBuff: false,
    buffId: 0,
  },
];