export const ChannellingComponents = [
  {
    name: "channel caster fake channel", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    ticksFromEnd: 0,
    fakeChannel: true,
  },
  {
    name: "channel caster default", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
  {
    name: "channel caster 0.5s", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: 16,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
  {
    name: "channel caster 1s", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: 33,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
  {
    name: "channel caster 1.5s", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: 50,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
  {
    name: "channel caster 2s", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: 66,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
  {
    name: "channel caster cero fire", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    ticksFromEnd: 12,
    fakeChannel: false,
  },
  {
    name: "channel caster granolah snipe charged", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,
    ticksFromEnd: 0,
    fakeChannel: false,
  },
];