export const HideUnitComponents = [
  {
    name: "hide unit angry explosion", 
    repeatInterval: 1, 
    startTick: 50,
    endTick: -1,
    doHide: true,
    preventMovement: true,
    removeNegativeBuffs: false,
    forceReselect: false,
  },
  {
    name: "hide unit allow movement", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    doHide: true,
    preventMovement: false,
    removeNegativeBuffs: false,
    forceReselect: false,
  },
  {
    name: "hide unit prevent movement", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    doHide: true,
    preventMovement: true,
    removeNegativeBuffs: false,
    forceReselect: false,
  },
  {
    name: "hide unit prevent movement reselect", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    doHide: true,
    preventMovement: false,
    removeNegativeBuffs: false,
    forceReselect: true,
  },
  {
    name: "hide unit scattering bullet start", 
    repeatInterval: 1, 
    startTick: 20,
    endTick: -1,
    doHide: true,
    preventMovement: false,
    removeNegativeBuffs: false,
    forceReselect: false,
  },
  {
    name: "hide unit yamcha r play dead", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    doHide: true,
    preventMovement: true,
    removeNegativeBuffs: false,
    forceReselect: false,
  },
  {
    name: "hide unit dk thrilla gorilla", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    doHide: false,
    preventMovement: true,
    removeNegativeBuffs: true,
    forceReselect: false,
  },
];