export const JumpComponents = [
  // {
  //   name: "jump zanzo dash",
  //   repeatInterval: 1, 
  //   startTick: 0,
  //   endTick: -1,
  //   duration: 24,
  //   maxHeight: 400,
  //   useSpeedToCastPoint: false,
  //   speed: -1,
  // },
  {
    name: "jump videl flying kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump saibaman bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 22,
    maxHeight: 300,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam kannonblast",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 40,
    maxHeight: 700,
    useSpeedToCastPoint: true,
    speed: 40,
  },
  {
    name: "jump nova rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump justice kick on hit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 15,
    maxHeight: 400,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump yamcha r sledgehammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 13,
    maxHeight: 400,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump california smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 700,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump hells gate sephiroth",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 800,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump new hampshire smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 300,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam mario fireball 1",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 11,
    startTimeRatio: 0,
    duration: 11,
    maxHeight: 350,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam mario fireball 2",
    repeatInterval: 1, 
    startTick: 11,
    endTick: 22,
    startTimeRatio: 0,
    duration: 11,
    maxHeight: 350,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam mario fireball 3",
    repeatInterval: 1, 
    startTick: 22,
    endTick: 33,
    startTimeRatio: 0,
    duration: 11,
    maxHeight: 350,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam mario fireball 4",
    repeatInterval: 1, 
    startTick: 33,
    endTick: -1,
    startTimeRatio: 0,
    duration: 11,
    maxHeight: 350,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump dragoon flourish",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump crono cleave",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 750,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam frog squash 1",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 33,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 650,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam frog squash 2",
    repeatInterval: 1, 
    startTick: 33,
    endTick: 66,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 650,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam frog squash 3",
    repeatInterval: 1, 
    startTick: 66,
    endTick: 99,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 650,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump frog drop kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0.5,
    duration: 16,
    maxHeight: 750,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump frog line bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 20,
    maxHeight: 200,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump robo bubble snap",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 99,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump ayla triple kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 12,
    maxHeight: 200,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam ayla ice toss",
    repeatInterval: 1, 
    startTick: 33,
    endTick: -1,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 500,
    useSpeedToCastPoint: true,
    speed: 50,
  },
  {
    name: "jump beam ayla cube toss",
    repeatInterval: 1, 
    startTick: 33,
    endTick: -1,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 500,
    useSpeedToCastPoint: true,
    speed: 60,
  },
  {
    name: "jump beam marle glacier",
    repeatInterval: 1, 
    startTick: 16,
    endTick: -1,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 400,
    useSpeedToCastPoint: true,
    speed: 40,
  },
  {
    name: "jump saitama leap",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 25,
    maxHeight: 2500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump dk barrel roll",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,
    startTimeRatio: 0,
    duration: 12,
    maxHeight: 400,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump dk jungle rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 30,
    maxHeight: 500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump jaco super elite combo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 22,
    startTimeRatio: 0,
    duration: 22,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump waluigi jump",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 33,
    startTimeRatio: 0,
    duration: 33,
    maxHeight: 500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump link bomb 1",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 12,
    maxHeight: 500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump link bomb 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 24,
    maxHeight: 500,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump majin vegeta final flash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    startTimeRatio: 0,
    duration: 60,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
]