import { Id } from "Common/Constants";

export const TempAbilityComponents = [
  {
    name: "temp ability tyrant lancer", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0LO"),
    oldAbility: FourCC("A0OX"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability brave cannon", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0I8"),
    oldAbility: FourCC("A0I9"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability heros flute armor aura", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0I5"),
    oldAbility: FourCC("A0IB"),
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability evil aura", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0DW"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability demonic blade", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0OA"),
    oldAbility: FourCC("A0O2"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability kannonblast", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0OW"),
    oldAbility: FourCC("A0IU"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability swap demon mark", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0O1"),
    oldAbility: FourCC("A0O0"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability disable god of destruction toppo", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0PC"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: false,
    disableAbility: true,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability ginyu pose fighting armor aura", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0PX"),
    oldAbility: FourCC("A0PT"),
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability dragonic rage crit", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0QS"),
    oldAbility: FourCC("A0QM"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: true,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability disable light bullet", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0QY"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: false,
    disableAbility: true,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability disable new trick", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0KU"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: false,
    disableAbility: true,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: false,
    linkCooldowns: -1,
  },  {
    name: "temp ability fervent rush", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0TA"),
    oldAbility: FourCC("A0T9"),
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability kid trunks sword of hope aura", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("S002"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability cero fire", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.ceroFire,
    oldAbility: Id.ceroCharge,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability heart of fire", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.heartOfFirePassive,
    oldAbility: Id.heartOfFire,
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: false,
    tempPermanence: true,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability blazing dynamo spell immunity", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: FourCC("A0VD"),
    oldAbility: 0,
    performSwap: false,
    enableAbility: false,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability hirudegarn flight", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.hirudegarnFlight,
    oldAbility: 0,
    performSwap: false,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability vegeta hakai", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.vegetaHakai,
    oldAbility: Id.bigBangAttack,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability vegeta hakai barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.vegetaHakaiBarrage,
    oldAbility: Id.energyBlastVolley,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: -1,
  },
  {
    name: "temp ability schala magic orbs 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaMagicOrbs2,
    oldAbility: Id.schalaMagicOrbs,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability schala protect 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaProtect2,
    oldAbility: Id.schalaProtect,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability schala protect 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaProtect2,
    oldAbility: Id.schalaProtect,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability schala teleport 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaTeleportation2,
    oldAbility: Id.schalaTeleportation,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability schala skygate 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaSkygate2,
    oldAbility: Id.schalaSkygate,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability schala seal 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.schalaMagicSeal2,
    oldAbility: Id.schalaMagicSeal,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -10,
  },
  {
    name: "temp ability sonic insta shield", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.sonicInstaShield,
    oldAbility: Id.sonicJump,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability special beast cannon", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.specialBeastCannon,
    oldAbility: Id.fatherSonKame,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: false,
    linkCooldowns: 0,
  },
  {
    name: "temp ability waluigi fireball", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.waluigiSuperFireball,
    oldAbility: Id.waluigiFireball,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
  {
    name: "temp ability rust gobble", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    newAbility: Id.rustGobble,
    oldAbility: Id.rustChomp,
    performSwap: true,
    enableAbility: true,
    disableAbility: false,
    addAbility: true,
    tempPermanence: false,
    equalizeLevels: true,
    linkCooldowns: -1,
  },
];