export const TimedLifeComponents = [
  // {
  //   name: "timed life lava pillars", 
  //   repeatInterval: 1, 
  //   startTick: 0,
  //   endTick: -1,
  //   duration: 50,
  // },
  {
    name: "timed life beam super 17 hell storm", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 12,
  },
  {
    name: "timed life beam robo laser spin", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 25,
  },
  {
    name: "timed life 30", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
  },
  {
    name: "timed life 33", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
  },
  {
    name: "timed life 35", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 35,
  },
  {
    name: "timed life 37", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 37,
  },
  {
    name: "timed life 40", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 40,
  },
  {
    name: "timed 44", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 44,
  },
  {
    name: "timed life 50", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 50,
  },
  {
    name: "timed life 66", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 66,
  },
  {
    name: "timed life 99", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 99,
  },
  {
    name: "timed life beam marle haste", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 70,
  },
];