export const TimedLifeComponents = [
  {
    name: "timed life beam mankind destruction attack", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 50,
  },
  {
    name: "timed life beam innocence breath", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 66,
  },
  // {
  //   name: "timed life lava pillars", 
  //   repeatInterval: 1, 
  //   startTick: 0,
  //   endTick: -1,
  //   duration: 50,
  // },
  {
    name: "timed life beam power blitz barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 99,
  },
  {
    name: "timed life beam justice flash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
  },
  {
    name: "timed life beam justice flash 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 37,
  },
  {
    name: "timed life beam galaxy dynamite", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
  },
  {
    name: "timed life beam death beam barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
  },
  {
    name: "timed life beam psychic rock throw", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 40,
  },
  {
    name: "timed life beam goten rock throw", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 35,
  },
  {
    name: "timed life beam die die missile barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 40,
  },
  {
    name: "timed life beam super ghost kamikaze attack", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 66,
  },
  {
    name: "timed life beam flame shot", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 35,
  },
  {
    name: "timed life beam dragon summon", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 45,
  },
  {
    name: "timed life beam crono slash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 30,
  },
  {
    name: "timed life beam robo laser spin", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 25,
  },
  {
    name: "timed life beam marle haste", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 70,
  },
  {
    name: "timed life beam super 17 flash bomber", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 40,
  },
  {
    name: "timed life beam super 17 hell storm", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 12,
  },
  {
    name: "timed life waluigi fireball", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 44,
  },
];