
export const AnimationComponents = [
  {
    name: "anim crono cyclone",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim crono slash",
    repeatInterval: 8,
    startTick: 0,
    endTick: 23,
    animationSpeed: 0,
    animationIndex: 2,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim crono cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim frog cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim robo tackle",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 6,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim saitama leap slam",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 1.0,
    animationIndex: 4,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim saitama serious punch",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 7,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  // {
  //   name: "anim dk roll",
  //   repeatInterval: 2,
  //   startTick: 0,
  //   endTick: -1,
  //   animationSpeed: 0,
  //   animationIndex: 7,
  //   animationString: "",
  //   addAnimationProperty: "",
  //   onlyApplyAtStart: false,
  //   resetAnimation: true,
  // },
  {
    name: "anim dk jungle rush",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 11,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
];