
export const AnimationComponents = [
  {
    name: "anim crono cyclone",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: -1,
    animationString: "",
    addAnimationProperty: "alternate",
    onlyApplyAtStart: true,
    resetAnimation: true,
  },
  {
    name: "anim crono slash",
    repeatInterval: 8,
    startTick: 0,
    endTick: 23,
    animationSpeed: 0,
    animationIndex: 2,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim crono cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
  {
    name: "anim frog cleave",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    animationSpeed: 0,
    animationIndex: 10,
    //didn't set animation index btw
    animationString: "",
    addAnimationProperty: "",
    onlyApplyAtStart: false,
    resetAnimation: true,
  },
];