import { AOEDamage } from "CustomAbility/AbilityComponent/AOEDamage";

/*

// Hero stats
constant integer   bj_HEROSTAT_STR             = 0
constant integer   bj_HEROSTAT_AGI             = 1
constant integer   bj_HEROSTAT_INT             = 2

constant attacktype         ATTACK_TYPE_NORMAL              = ConvertAttackType(0)
constant attacktype         ATTACK_TYPE_MELEE               = ConvertAttackType(1)
constant attacktype         ATTACK_TYPE_PIERCE              = ConvertAttackType(2)
constant attacktype         ATTACK_TYPE_SIEGE               = ConvertAttackType(3)
constant attacktype         ATTACK_TYPE_MAGIC               = ConvertAttackType(4)
constant attacktype         ATTACK_TYPE_CHAOS               = ConvertAttackType(5)
constant attacktype         ATTACK_TYPE_HERO                = ConvertAttackType(6)

// damage type is pointless

constant weapontype         WEAPON_TYPE_WHOKNOWS            = ConvertWeaponType(0)
constant weapontype         WEAPON_TYPE_METAL_LIGHT_CHOP    = ConvertWeaponType(1)
constant weapontype         WEAPON_TYPE_METAL_MEDIUM_CHOP   = ConvertWeaponType(2)
constant weapontype         WEAPON_TYPE_METAL_HEAVY_CHOP    = ConvertWeaponType(3)
constant weapontype         WEAPON_TYPE_METAL_LIGHT_SLICE   = ConvertWeaponType(4)
constant weapontype         WEAPON_TYPE_METAL_MEDIUM_SLICE  = ConvertWeaponType(5)
constant weapontype         WEAPON_TYPE_METAL_HEAVY_SLICE   = ConvertWeaponType(6)
constant weapontype         WEAPON_TYPE_METAL_MEDIUM_BASH   = ConvertWeaponType(7)
constant weapontype         WEAPON_TYPE_METAL_HEAVY_BASH    = ConvertWeaponType(8)
constant weapontype         WEAPON_TYPE_METAL_MEDIUM_STAB   = ConvertWeaponType(9)
constant weapontype         WEAPON_TYPE_METAL_HEAVY_STAB    = ConvertWeaponType(10)
constant weapontype         WEAPON_TYPE_WOOD_LIGHT_SLICE    = ConvertWeaponType(11)
constant weapontype         WEAPON_TYPE_WOOD_MEDIUM_SLICE   = ConvertWeaponType(12)
constant weapontype         WEAPON_TYPE_WOOD_HEAVY_SLICE    = ConvertWeaponType(13)
constant weapontype         WEAPON_TYPE_WOOD_LIGHT_BASH     = ConvertWeaponType(14)
constant weapontype         WEAPON_TYPE_WOOD_MEDIUM_BASH    = ConvertWeaponType(15)
constant weapontype         WEAPON_TYPE_WOOD_HEAVY_BASH     = ConvertWeaponType(16)
constant weapontype         WEAPON_TYPE_WOOD_LIGHT_STAB     = ConvertWeaponType(17)
constant weapontype         WEAPON_TYPE_WOOD_MEDIUM_STAB    = ConvertWeaponType(18)
constant weapontype         WEAPON_TYPE_CLAW_LIGHT_SLICE    = ConvertWeaponType(19)
constant weapontype         WEAPON_TYPE_CLAW_MEDIUM_SLICE   = ConvertWeaponType(20)
constant weapontype         WEAPON_TYPE_CLAW_HEAVY_SLICE    = ConvertWeaponType(21)
constant weapontype         WEAPON_TYPE_AXE_MEDIUM_CHOP     = ConvertWeaponType(22)
constant weapontype         WEAPON_TYPE_ROCK_HEAVY_BASH     = ConvertWeaponType(23)
*/
export module BASE {
  export const KAME_DPS = 0.0115;
  export const KAME_EXPLOSION = 0.053;
  export const SPIRIT_BOMB_DPS = 0.0075;
  export const SPIRIT_BOMB_EXPLOSION = 0.25;
  export const DFIST_DPS = 0.013;
  export const DFIST_EXPLOSION = 0.25;
}

export const DEFAULT_MAX_DAMAGE_TICKS = 12;

export const AOEDamageComponents = [
  // used for kame
  // note: i named the dmg components differently
  // so it'd be easier to fiddle with the numbers without having to constantly
  // rechange the name of the component in the beam/ability
  // copy from here
  {
    name: "damage kame dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // to here, and replace with unique name
  {
    name: "damage kame explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // god kame
  {
    name: "damage god kame dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage god kame explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 450,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // used for spirit bomb
  {
    name: "damage spirit bomb dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage spirit bomb explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // used for dfist
  {
    name: "damage dragon fist dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 320,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 25,
    damageData: {
      multiplier: BASE.DFIST_DPS,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage dragon fist explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // super dragon fist
  {
    name: "damage super dragon fist dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 30,
    damageData: {
      multiplier: BASE.DFIST_DPS * 1.05,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage super dragon fist explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 1.23,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // galick gun
  {
    name: "damage galick gun dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage galick gun explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // final flash
  {
    name: "damage final flash dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 10,
    damageData: {
      multiplier: BASE.KAME_DPS * 2.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage final flash explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // big bang attack
  {
    name: "damage big bang attack explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.85,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // energy blast volley
  {
    name: "damage energy blast volley dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.15,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // masenko 
  // gohan 7 lvls
  // cell 8 lvls
  {
    name: "damage masenko dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.15,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // twin dragon shot
  {
    name: "damage twin dragon shot dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage twin dragon shot explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.0,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // father-son kame goku
  {
    name: "damage father-son kame goku dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 700,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 30,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.05,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // super dragon flight
  {
    name: "damage super dragon flight dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 30,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.5,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // finish buster 
  {
    name: "damage finish buster dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage finish buster explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // heat dome attack initial explosion
  {
    name: "damage heat dome attack explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.8,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // burning attack 
  {
    name: "damage burning attack dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.3,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage burning attack explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 2.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // blazing rush
  {
    name: "damage blazing rush explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.4,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // special beam cannon
  // piccolo 10 lvls, cell 10 lvls
  {
    name: "damage special beam cannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // hellzone grenade
  {
    name: "damage hellzone grenade dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 200,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.03,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage hellzone grenade explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.27,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // tyrant breaker
  {
    name: "damage tyrant breaker dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 25,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.DFIST_DPS * 1.5,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam tyrant lancer dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.95,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam tyrant lancer explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // saiyan spirit
  {
    name: "damage saiyan spirit dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 25,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 310,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.DFIST_DPS * 2.5,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam saiyan spirit dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 280,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam saiyan spirit explosion",
    repeatInterval: 1,
    startTick: 32,
    endTick: 32,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.75,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // riot javelin
  {
    name: "damage beam riot javelin dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 320,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam riot javelin explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // rebellion spear
  {
    name: "damage rebellion spear dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 33,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.75,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // angry shout
  {
    name: "damage angry shout dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 50,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.5,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // pan immolation
  {
    name: "damage pan immolation dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 66,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.03,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // maiden blast beam
  {
    name: "damage beam maiden blast dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam maiden blast explosion",
    repeatInterval: 1,
    startTick: 50,
    endTick: 50,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // reliable friend beam
  {
    name: "damage beam reliable friend dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.0,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam reliable friend explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.85,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // power blitz
  {
    name: "damage power blitz dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage power blitz explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.7,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // power blitz barrage
  {
    name: "damage power blitz barrage dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.18,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage power blitz barrage explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.18,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // barrier prison
  {
    name: "damage barrier prison dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.08,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // barrier wall
  {
    name: "damage barrier wall dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.01,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // super electric strike
  {
    name: "damage super electric strike dps",
    repeatInterval: 16,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.072 * 16,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // videl punch
  {
    name: "damage videl punch",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_FIXED,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.35,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // videl kick
  {
    name: "damage videl kick",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.35,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // videl flying kick
  {
    name: "damage videl flying kick dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.65,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage videl flying kick explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.65,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // javelin throw
  {
    name: "damage javelin throw dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 200,
    onlyDamageCapHeroes: false,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.12,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // whirlwind tempest
  {
    name: "damage whirlwind tempest dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.75,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // korin flag
  {
    name: "damage korin flag explosion",
    repeatInterval: 1,
    startTick: 16,
    endTick: 16,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 3.5,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // last stand
  {
    name: "damage last stand dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.05,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage last stand explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.4,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // brave slash
  {
    name: "damage brave slash",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_FIXED,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.25,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // brave cannon
  {
    name: "damage brave cannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.05,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // shining sword
  {
    name: "damage shining sword explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 4,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.18,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage shining sword bonus buff explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 4,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.07,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: true,
    buffId: FourCC("B01H"),
  },
  // toppo justice flash
  {
    name: "damage justice flash dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage justice flash explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.13,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // justice flash 2
  {
    name: "damage justice flash 2 dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage justice flash 2 explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.3,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // justice punch
  {
    name: "damage justice punch explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.25,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // justice hold
  {
    name: "damage justice hold dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_TARGET_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 50,
    onlyDamageCapHeroes: false,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.17,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // 13 energy beam
  {
    name: "damage energy beam dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 50,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.23,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // ss deadly hammer
  {
    name: "damage ss deadly hammer dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 25,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.4,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // ss deadly bomber
  {
    name: "damage ss deadly bomber dps",
    repeatInterval: 16,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.35 * 16,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // 13 nuke 
  {
    name: "damage nuke dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.35,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage nuke explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // 13 overcharge
  {
    name: "damage overcharge dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 230,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.33,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // babidi
  {
    name: "damage target haretsu explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_LAST_CAST_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 50,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 1.9,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // buu flesh attack
  {
    name: "damage target flesh attack explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_LAST_CAST_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 50,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // evil spear
  {
    name: "damage evil spear dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 100,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 2,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // innocence breath
  {
    name: "damage innocence breath dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.21,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // angry explosion
  {
    name: "damage angry explosion dps",
    repeatInterval: 1,
    startTick: 50,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage angry explosion explosion",
    repeatInterval: 1,
    startTick: 50,
    endTick: 50,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.75,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // mankind attack
  {
    name: "damage mankind destruction attack dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 200,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.7,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // energy punch
  {
    name: "damage energy punch dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 20,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.6,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // power level rising
  // has 7 lvls
  {
    name: "damage power level rising explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.8,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // planet crusher
  {
    name: "damage planet crusher dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage planet crusher explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // gigantic roar dps
  {
    name: "damage gigantic roar dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.1,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // gigantic omegastorm
  {
    name: "damage gigantic omegastorm dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage gigantic omegastorm explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // solar kame
  {
    name: "damage solar kame dps charging",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS * 2,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage solar kame dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 700,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 120,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.63,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage solar kame explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.75,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // death beam
  {
    name: "damage death beam frieza dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.KAME_DPS * 2.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // nova chariot (match with dfist but agi-version)
  {
    name: "damage nova chariot dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 25,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.85,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // supernova golden, upped spirit bomb dmg
  {
    name: "damage supernova golden dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 1.2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage supernova golden explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 1.25,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // double sunday
  {
    name: "damage double sunday dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage double sunday explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // saturday crash
  {
    name: "damage beam saturday crash dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam saturday crash explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 350,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.6,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // behind you
  {
    name: "damage behind you dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: 20,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_DPS * 0.7,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // giant storm
  {
    name: "damage giant storm dps outer",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 750,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.1,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage giant storm dps inner",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.25,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage giant storm explosion outer",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 750,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage giant storm explosion inner",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.1,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // blazing storm
  {
    name: "damage target blazing storm explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_FIXED,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.17,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // break cannon
  {
    name: "damage beam break cannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.8,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // saibaman bomb
  {
    name: "damage saibaman bomb explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 450,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.45,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // saibaman acid
  {
    name: "damage saibaman acid dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.25,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // energy drain moro
  {
    name: "damage target energy drain moro explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_FIXED,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // energy ball moro
  {
    name: "damage energy ball moro dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_DPS * 0.65,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage energy ball moro explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.65,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // lava burst
  {
    name: "damage lava burst dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.125,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage lava burst explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.115,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // lava pillars
  {
    name: "damage target lava pillars",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_DYNAMIC,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 0.5,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // saibaman bomb
  {
    name: "damage android bomb item explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: 5.0,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // rakshasa claw
  {
    name: "damage rakshasa claw dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.36,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // devil claw
  {
    name: "damage devil claw dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.18,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // demonic blade
  {
    name: "damage demonic blade",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.27,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // hells gate
  {
    name: "damage hells gate dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 400,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage hells gate explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.45,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // lightning shower rain
  {
    name: "damage lightning shower rain dps",
    repeatInterval: 1,
    startTick: 50,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 8,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.1,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage lightning shower rain explosion",
    repeatInterval: 1,
    startTick: 50,
    endTick: 50,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.22,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // krown toss
  {
    name: "damage krown toss dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 7,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.85,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage krown toss return dps",
    repeatInterval: 1,
    startTick: 51,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.85,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage krown toss return bonus dps",
    repeatInterval: 1,
    startTick: 51,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 2,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.05,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: true,
    buffId: FourCC("B02W"),
  },
  // kharge
  {
    name: "damage kharge explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 250,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 3,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.17,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // hand kannon
  {
    name: "damage hand kannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_TARGET_POINT_DYNAMIC,
    scaleDamageToSourceHp: false,
    useLastCastPoint: true,
    aoe: 250,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.25,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // beam hand kannon
  {
    name: "damage beam hand kannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 300,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 8,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.7,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // monkey smasher
  {
    name: "damage monkey smasher explosion",
    repeatInterval: 8,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 2,
    damageData: {
      multiplier: BASE.KAME_EXPLOSION * 1.75,
      attribute: bj_HEROSTAT_STR,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // blast-o-matic
  {
    name: "damage blast-o-matic dps charging",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 500,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS * 2,
    damageData: {
      // 0.2
      multiplier: BASE.KAME_DPS * 2,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage blast-o-matic dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 700,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 97,
    damageData: {
      // 0.4
      multiplier: BASE.KAME_DPS * 4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage blast-o-matic explosion",
    repeatInterval: 1,
    startTick: -1,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 800,
    onlyDamageCapHeroes: true,
    maxDamageTicks: 1,
    damageData: {
      // 1.0
      multiplier: BASE.KAME_EXPLOSION * 10,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // frost claws
  {
    name: "damage frost claws explosion",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 275,
    onlyDamageCapHeroes: false,
    maxDamageTicks: 1,
    damageData: {
      multiplier: BASE.SPIRIT_BOMB_EXPLOSION * 0.1,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // ice slash
  {
    name: "damage ice slash",
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: false,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: AOEDamage.UNLIMITED_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.DFIST_EXPLOSION * 0.58,
      attribute: bj_HEROSTAT_AGI,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  // ice cannon
  {
    name: "damage beam ice cannon dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 1.4,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: false,
    buffId: 0,
  },
  {
    name: "damage beam ice cannon bonus buff dps",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    damageSource: AOEDamage.SOURCE_UNIT,
    scaleDamageToSourceHp: true,
    useLastCastPoint: false,
    aoe: 600,
    onlyDamageCapHeroes: true,
    maxDamageTicks: DEFAULT_MAX_DAMAGE_TICKS,
    damageData: {
      multiplier: BASE.KAME_DPS * 0.7,
      attribute: bj_HEROSTAT_INT,
      attackType: 6,
      damageType: 0,
      weaponType: 0,
    },
    requireBuff: true,
    buffId: FourCC("B02T"),
  },
];