import { AOEKnockback } from "CustomAbility/AbilityComponent/AOEKnockback";

export const AOEKnockbackComponents = [
  // spirit bomb stronger knockback
  // copy from here
  {
    name: "knockback 1tick 15speed 0angle 300aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 15, 
      angle: 0, 
      aoe: 300,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  {
    name: "knockback spirit bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 9, 
      angle: 180, 
      aoe: 350,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // to here, and replace with unique name
  // kame light knockback
  {
    name: "knockback 1tick 10speed 0angle 250aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 10, 
      angle: 0, 
      aoe: 250,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  {
    name: "knockback kame",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 6, 
      angle: 180, 
      aoe: 250,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // super dragon flight
  {
    name: "knockback super dragon flight",
    repeatInterval: 1, 
    startTick: 10,
    endTick: -1,
    knockbackData: {
      speed: 20, 
      angle: 0, 
      aoe: 200,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // heat dome attack
  {
    name: "knockback heat dome attack",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 9,
    knockbackData: {
      speed: 23, 
      angle: 0, 
      aoe: 400,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // hellzone grenade
  // {
  //   name: "knockback hellzone grenade",
  //   repeatInterval: 1, 
  //   startTick: 0,
  //   endTick: -1,
  //   knockbackData: {
  //     speed: 1, 
  //     angle: 0, 
  //     aoe: 250,
  //   },
  //   affectAllies: false,
  // },
  // videl punch
  {
    name: "knockback videl punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 4,
    knockbackData: {
      speed: 25, 
      angle: 0, 
      aoe: 300,
    },
    knockbackSource: AOEKnockback.SOURCE_TARGET_POINT,
    useLastCastPoint: true,
    reflectBeams: true,
    affectAllies: false,
  },
  // videl kick
  {
    name: "knockback videl kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 7,
    knockbackData: {
      speed: 25, 
      angle: 0, 
      aoe: 350,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: true,
    affectAllies: false,
  },
  // videl flying kick
  {
    name: "knockback videl flying kick",
    repeatInterval: 1, 
    startTick: -1,
    endTick: -1,
    knockbackData: {
      speed: 50, 
      angle: 0, 
      aoe: 400,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: true,
    affectAllies: false,
  },
  // javelin throw
  {
    name: "knockback javelin throw",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 55, 
      angle: 180, 
      aoe: 150,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // ss deadly hammer reverse knockback
  {
    name: "knockback ss deadly hammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,
    knockbackData: {
      speed: 10, 
      angle: 180, 
      aoe: 400,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // android barrier knockback
  {
    name: "knockback android barrier",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 99,
    knockbackData: {
      speed: 45, 
      angle: 0, 
      aoe: 550,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // broly energy punch
  {
    name: "knockback energy punch reverse",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 19,
    knockbackData: {
      speed: -30, 
      angle: 0, 
      aoe: 500,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  {
    name: "knockback energy punch",
    repeatInterval: 1, 
    startTick: 19,
    endTick: -1,
    knockbackData: {
      speed: 30, 
      angle: 0, 
      aoe: 500,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // broly power level rising
  {
    name: "knockback power level rising",
    repeatInterval: 1, 
    startTick: 1,
    endTick: -1,
    knockbackData: {
      speed: 15, 
      angle: 0, 
      aoe: 350,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // big bang attack reverse knockback
  {
    name: "knockback 1tick 15speed 180angle 400aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 15, 
      angle: 180, 
      aoe: 400,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  {
    name: "knockback 1tick 25speed 180angle 250aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 25, 
      angle: 180, 
      aoe: 250,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // dfist knock-in
  {
    name: "knockback dfist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 10, 
      angle: 180, 
      aoe: 250,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // energy blast volley minor knockback
  {
    name: "knockback 1tick 5speed 0angle 250aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 5, 
      angle: 0, 
      aoe: 250,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // angry shout large aoe knockback
  {
    name: "knockback angry shout",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 20, 
      angle: 0, 
      aoe: 700,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // reliable friend
  {
    name: "knockback reliable friend",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 10, 
      angle: 0, 
      aoe: 400,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // babidi barrier knockback
  {
    name: "knockback babidi barrier",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 15, 
      angle: 0, 
      aoe: 650,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // evil spear knock in
  {
    name: "knockback evil spear",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 60, 
      angle: 180, 
      aoe: 100,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // cooler deafening wave
  {
    name: "knockback 1tick 25speed 0angle 500aoe",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 25, 
      angle: 0, 
      aoe: 500,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // solar kame
  {
    name: "knockback solar kame",
    repeatInterval: 1, 
    startTick: 111,
    endTick: -1,
    knockbackData: {
      speed: 40, 
      angle: 180, 
      aoe: 500,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // raditz behind you
  {
    name: "knockback behind you",
    repeatInterval: 1, 
    startTick: 9,
    endTick: -1,
    knockbackData: {
      speed: 35, 
      angle: 0, 
      aoe: 600,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // power blitz
  {
    name: "knockback power blitz",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 4, 
      angle: 180, 
      aoe: 300,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // power blitz barrage
  {
    name: "knockback power blitz barrage",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 1.5, 
      angle: 180, 
      aoe: 300,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
  // super electric strike
  {
    name: "knockback super electric strike",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    knockbackData: {
      speed: 2, 
      angle: 180, 
      aoe: 300,
    },
    knockbackSource: AOEKnockback.SOURCE_UNIT,
    useLastCastPoint: false,
    reflectBeams: false,
    affectAllies: false,
  },
];