export const BarrierComponents = [
  {
    name: "barrier barrier prison", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    aoe: 300,
    repelOutsidersSpeed: 15,
    affectAllies: true,
    canWalkOut: false,
  },
  {
    name: "barrier barrier wall", 
    repeatInterval: 1, 
    startTick: 2,
    endTick: -1,
    aoe: 250,
    repelOutsidersSpeed: 15,
    affectAllies: true,
    canWalkOut: true,
  },
  {
    name: "barrier last stand", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    aoe: 500,
    repelOutsidersSpeed: 15,
    affectAllies: true,
    canWalkOut: false,
  },
  {
    name: "barrier cage of light", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    aoe: 600,
    repelOutsidersSpeed: 15,
    affectAllies: true,
    canWalkOut: false,
  },
  {
    name: "barrier schala magic seal", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    aoe: 400,
    repelOutsidersSpeed: 15,
    affectAllies: true,
    canWalkOut: false,
  },
];