export const BeamComponents = [
  // copy from here
  { 
    name: "beam kamehameha",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.02,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 30,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 0,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage kame dps" },
      { name: "damage kame explosion" },
      { name: "knockback 1tick 10speed 0angle 250aoe" },
      { name: "sfx beam kamehameha" },
    ],
  },
  // to here, and replace with unique name
  { 
    name: "beam spirit bomb",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.05,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 25,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 10,
    durationIncPerDelay: 15,
    heightVariation: {
      start: 600,
      finish: 0,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage spirit bomb dps" },
      { name: "damage spirit bomb explosion" },
      { name: "knockback 1tick 15speed 0angle 300aoe" },
      { name: "sfx beam spirit bomb" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam galick gun",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.02,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 40,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 7,
    durationIncPerDelay: 6,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 0,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage kame dps" },
      { name: "damage kame explosion" },
      { name: "knockback 1tick 10speed 0angle 250aoe" },
      { name: "sfx beam galick gun" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam big bang attack",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.03,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 50,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 150,
      finish: 0,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage spirit bomb dps" },
      { name: "damage big bang attack explosion" },
      { name: "knockback 1tick 15speed 180angle 400aoe" },
      { name: "sfx beam big bang attack" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam final flash",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.04,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 50,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: false,
    beamUnitType: "hpea",
    components: [
      { name: "damage final flash dps" },
      { name: "damage final flash explosion" },
      { name: "sfx beam final flash" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam twin dragon shot",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.02,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 35,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 7,
    durationIncPerDelay: 25,
    heightVariation: {
      start: 100,
      finish: 300,
      scaling: 0,
    },
    isTracking: true,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage twin dragon shot dps" },
      { name: "damage twin dragon shot explosion" },
      { name: "dodge homing beam 120angle" },
      { name: "sfx beam kamehameha" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam masenko",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.03,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 40,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 4,
    durationIncPerDelay: 17,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 0,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage masenko dps" },
      { name: "damage kame explosion" },
      { name: "stun masenko" },
      { name: "sfx beam masenko" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam planet crusher",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.05,
    beamHpAttribute: bj_HEROSTAT_STR,
    speed: 25,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 7,
    durationIncPerDelay: 11,
    heightVariation: {
      start: 600,
      finish: 0,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage planet crusher dps" },
      { name: "damage planet crusher explosion" },
      { name: "knockback 1tick 15speed 0angle 300aoe" },
      { name: "sfx beam planet crusher" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam gigantic roar",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.03,
    beamHpAttribute: bj_HEROSTAT_STR,
    speed: 40,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 9,
    durationIncPerDelay: 17,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: false,
    beamUnitType: "hpea",
    components: [
      { name: "damage gigantic roar dps" },
      { name: "knockback 1tick 15speed 0angle 300aoe" },
      { name: "sfx beam gigantic roar" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam gigantic omegastorm",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.04,
    beamHpAttribute: bj_HEROSTAT_STR,
    speed: 50,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 6,
    durationIncPerDelay: 11,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage gigantic omegastorm dps" },
      { name: "damage gigantic omegastorm explosion" },
      { name: "knockback 1tick 25speed 0angle 300aoe" },
      { name: "sfx beam gigantic omegastorm" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam death beam frieza",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.01,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 40,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 1,
    durationIncPerDelay: 6,
    heightVariation: {
      start: 50,
      finish: 25,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage death beam frieza dps" },
      { name: "sfx beam death beam frieza" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam supernova cooler",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.05,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 25,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 10,
    durationIncPerDelay: 15,
    heightVariation: {
      start: 600,
      finish: 0,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage spirit bomb dps" },
      { name: "damage spirit bomb explosion" },
      { name: "knockback 1tick 15speed 0angle 300aoe" },
      { name: "sfx beam supernova cooler" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam supernova golden",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.1,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 25,
    aoe: 300,
    clashingDelayTicks: 2,
    maxDelayTicks: 10,
    durationIncPerDelay: 15,
    heightVariation: {
      start: 700,
      finish: 0,
      scaling: 1,
    },
    isTracking: true,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage supernova golden dps" },
      { name: "damage supernova golden explosion" },
      { name: "knockback 1tick 15speed 0angle 300aoe" },
      { name: "sfx beam supernova golden" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam homing kamehameha",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.5,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 25,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 75,
      finish: 75,
      scaling: 0,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage kame dps" },
      { name: "damage kame explosion" },
      { name: "dodge homing beam 120angle" },
      { name: "sfx beam kamehameha" },
    ],
  },
  // -------------------------------------------
  { 
    name: "beam big bang kamehameha kame",
    repeatInterval: 1,
    startTick: 20,
    endTick: -1,
    beamHpMult: 0.02,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 30,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 100,
      finish: 100,
      scaling: 0,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "damage kame dps" },
      { name: "damage kame explosion" },
      { name: "knockback 1tick 10speed 0angle 250aoe" },
      { name: "sfx beam kamehameha" },
    ],
  },
  { 
    name: "beam big bang kamehameha",
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    beamHpMult: 0.05,
    beamHpAttribute: bj_HEROSTAT_INT,
    speed: 0,
    aoe: 300,
    clashingDelayTicks: 1,
    maxDelayTicks: 6,
    durationIncPerDelay: 12,
    heightVariation: {
      start: 150,
      finish: 0,
      scaling: 1,
    },
    isTracking: false,
    isFixedAngle: false,
    canClashWithHero: true,
    beamUnitType: "hpea",
    components: [
      { name: "beam big bang kamehameha kame" },
      { name: "damage spirit bomb dps" },
      { name: "damage big bang attack explosion" },
      { name: "flying dash big bang kamehameha" },
      { name: "knockback 1tick 15speed 180angle 400aoe" },
      { name: "sfx beam big bang attack" },
    ],
  },
];