import { Dash } from "CustomAbility/AbilityComponent/Dash";

export const DashComponents = [
  {
    name: "dash ground point 5dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point 10dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 10,
  },
  {
    name: "dash ground point 15dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  {
    name: "dash ground point 20dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  {
    name: "dash ground point 25dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  {
    name: "dash ground point 30dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point 35dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  {
    name: "dash ground point 40dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  {
    name: "dash ground point 45dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 45,
  },
  {
    name: "dash ground point 50dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 50,
  },
  // ----------------------------
  // max power
  {
    name: "dash ground forward max power",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  {
    name: "dash ground forward mastered ultra instinct",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point dragon fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  {
    name: "dash ground point super dragon fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  {
    name: "dash ground point super dragon flight",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 28,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground forward super saiyan rage",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point tyrant breaker",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  {
    name: "dash ground forward rebellion spear",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  {
    name: "dash ground point saiyan spirit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point saiyan spirit pushback",
    repeatInterval: 1, 
    startTick: 20,
    endTick: 27,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 40,
  },
  {
    name: "dash ground point reliable friend",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point ss deadly hammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // energy punch
  {
    name: "dash ground point energy punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  {
    name: "dash ground point gigantic roar pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 25,
  },
  // flying dash forwards facing
  {
    name: "dash flying forward 5dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  // big bang kamehameha bang 
  {
    name: "dash flying forward big bang kamehameha",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // hellzone grenade delayed dash to target unit
  {
    name: "dash flying point hellzone grenade",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 66,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 55,
  },
  {
    name: "dash flying unit hellzone grenade",
    repeatInterval: 1, 
    startTick: 99,
    endTick: -1,
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 55,
  },
  // videl speed boost
  {
    name: "dash ground forward videl speed boost",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2,
  },
  // videl flying kick
  {
    name: "dash ground point videl flying kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 40,
  },
  // whirlwind tempest
  {
    name: "dash ground point whirlwind tempest",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // last stand
  {
    name: "dash ground forward last stand",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  // shining sword
  {
    name: "dash ground point shining sword",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 39,
  },
  // justice punch
  {
    name: "dash ground point justice punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point justice punch 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  // justice tornado
  {
    name: "dash ground forward justice tornado",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  // justice tornado 2
  {
    name: "dash ground forward justice tornado 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // god of destruction
  {
    name: "dash ground forward god of destruction toppo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // light bullet
  {
    name: "dash ground point light bullet",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  // justice kick
  {
    name: "dash ground forward justice kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 10,
  },
  {
    name: "dash ground forward justice kick 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  // super max
  {
    name: "dash ground forward super maximum light speed mode",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 10,
  },
  // ----------------------------
  // cell-x
  {
    name: "dash ground forward cell-x pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 4,
  },
  // nova chariot
  {
    name: "dash ground point nova chariot",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  // behind you
  {
    name: "dash ground point behind you pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 10,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 30,
  },
  // saibaman bomb
  {
    name: "dash ground unit saibaman bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 37,
  },
  // power level sharing
  {
    name: "dash forward power level sharing",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // bunkai teleport dash
  {
    name: "dash ground point bunkai teleport",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 60,
  },
  // lightning shower rain
  {
    name: "dash flying forward lightning shower rain",
    repeatInterval: 1, 
    startTick: 50,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 50,
  },
  // belly armor
  {
    name: "dash ground forward belly armor",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 8,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // krown toss
  {
    name: "dash flying forward krown toss",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 50,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  {
    name: "dash flying caster krown toss return",
    repeatInterval: 1, 
    startTick: 51,
    endTick: -1,
    targetDirection: Dash.DIRECTION_CASTER_POINT,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 63,
  },
  // kharge
  {
    name: "dash ground point kharge",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  // ginyu pose fighting
  {
    name: "dash ground forward ginyu pose fighting",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // nova strike
  {
    name: "dash ground point nova strike",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // emperors throne
  {
    name: "dash ground forward emperors throne",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 3,
  },
  // impaling rush
  {
    name: "dash ground point impaling rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // nova rush
  {
    name: "dash ground point nova rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // nova rush golden
  {
    name: "dash ground point nova rush golden",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  // cage of light
  {
    name: "dash flying point cage of light",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 33,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: true,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 66,
  },
  // shadow fist
  {
    name: "dash ground point shadow fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  // dragonic rage
  {
    name: "dash ground forward dragonic rage",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 4,
  },
  // ---
  // saga zanzo
  {
    name: "dash ground point zanzo saga",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    isFlying: false,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 32,
  },
  // saga max power
  {
    name: "dash ground forward max power saga",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    isFlying: false,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
]