import { Dash } from "CustomAbility/AbilityComponent/Dash";

export const DashComponents = [
  {
    name: "dash ground point 5dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point 10dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 10,
  },
  {
    name: "dash ground point 15dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  {
    name: "dash ground point 20dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  {
    name: "dash ground point 25dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  {
    name: "dash ground point 30dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point 35dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  {
    name: "dash ground point 40dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  {
    name: "dash ground point 45dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 45,
  },
  {
    name: "dash ground point 50dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 50,
  },
  // ----------------------------
  // zanzo
  {
    name: "dash zanzo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_ZANZO,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  // max power
  {
    name: "dash ground forward max power",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // bankai
  {
    name: "dash ground forward bankai",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  {
    name: "dash ground forward mastered ultra instinct",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point dragon fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 17,
  },
  {
    name: "dash ground point super dragon fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 22,
  },
  {
    name: "dash ground point super dragon flight",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 30,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // potential unleashed
  {
    name: "dash ground forward potential unleashed",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  {
    name: "dash ground forward super saiyan rage",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  {
    name: "dash ground point tyrant breaker",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  {
    name: "dash ground forward rebellion spear",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 17.5,
  },
  {
    name: "dash ground point saiyan spirit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point saiyan spirit pushback",
    repeatInterval: 1, 
    startTick: 20,
    endTick: 27,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 40,
  },
  {
    name: "dash ground point reliable friend",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 30,
  },
  {
    name: "dash ground point ss deadly hammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // energy punch
  {
    name: "dash ground point energy punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  {
    name: "dash ground point gigantic roar pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 25,
  },
  // flying dash forwards facing
  {
    name: "dash flying forward 5dist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  // big bang kamehameha bang 
  {
    name: "dash flying forward big bang kamehameha",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 20,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // hellzone grenade delayed dash to target unit
  {
    name: "dash flying point hellzone grenade",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 66,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 55,
  },
  {
    name: "dash flying unit hellzone grenade",
    repeatInterval: 1, 
    startTick: 99,
    endTick: -1,
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 55,
  },
  // videl speed boost
  {
    name: "dash ground forward videl speed boost",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2.5,
  },
  // videl flying kick
  {
    name: "dash ground point videl flying kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 45,
  },
  // whirlwind tempest
  {
    name: "dash ground point whirlwind tempest",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 22,
  },
  // last stand
  {
    name: "dash ground forward last stand",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  // shining sword
  {
    name: "dash ground point shining sword",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 39,
  },
  // ultimate burning warrior
  {
    name: "dash ground forward ultimate burning warrior",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  {
    name: "dash ground forward ultimate burning warrior 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 3,
  },
  // justice punch
  {
    name: "dash ground point justice punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 33,
  },
  {
    name: "dash ground point justice punch 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 44,
  },
  // justice tornado
  {
    name: "dash ground forward justice tornado",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  // justice tornado 2
  {
    name: "dash ground forward justice tornado 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // god of destruction
  {
    name: "dash ground forward god of destruction toppo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // light bullet
  {
    name: "dash ground point light bullet",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 45,
  },
  // justice kick
  {
    name: "dash ground forward justice kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 10,
  },
  {
    name: "dash ground forward justice kick 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 12,
  },
  // super max
  {
    name: "dash ground forward super maximum light speed mode",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 8,
  },
  // scattering bullet
  {
    name: "dash flying target scattering bullet 1",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 45,
    distance: 22,
  },
  {
    name: "dash flying target scattering bullet 2",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 135,
    distance: 22,
  },
  {
    name: "dash flying target scattering bullet 3",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 225,
    distance: 22,
  },
  {
    name: "dash flying target scattering bullet 4",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 315,
    distance: 22,
  },
  // yamcha r light punch
  {
    name: "dash ground forward yamcha r light punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 4,
  },
  // yamcha r medium punch
  {
    name: "dash ground forward yamcha r medium punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 3,
  },
  // yamcha r heavy punch
  {
    name: "dash ground forward yamcha r heavy punch",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2,
  },
  // yamcha r dash left
  {
    name: "dash ground forward yamcha r dash left",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 90,
    distance: 35,
  },
  // yamcha r dash forward
  {
    name: "dash ground forward yamcha r dash forward",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 35,
  },
  // yamcha r dash right
  {
    name: "dash ground forward yamcha r dash right",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 270,
    distance: 35,
  },
  // yamcha r super spirit ball
  {
    name: "dash flying forward yamcha r super spirit ball",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 30,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 60,
  },
  {
    name: "dash flying caster yamcha r super spirit ball return",
    repeatInterval: 1, 
    startTick: 31,
    endTick: -1,
    targetDirection: Dash.DIRECTION_CASTER_POINT,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 50,
  },
  // yamcha r sledgehammer
  {
    name: "dash ground forward yamcha r sledgehammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 10,
  },
  // yamcha r meteor crash
  {
    name: "dash ground forward yamcha r meteor crash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 6,
  },
  // yamcha r meteor crash
  {
    name: "dash ground forward yamcha r uppercut",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 3,
  },
  // yamcha r wolf fang hurricane
  {
    name: "dash ground forward yamcha r wolf fang hurricane",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // yamcha r reverse wolf fang blast
  {
    name: "dash ground forward yamcha r reverse wolf fang blast",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 8,
  },
  // yamcha r wolf fang fist
  {
    name: "dash ground forward yamcha r wolf fang fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 6,
  },
  // yamcha r spirit ball
  {
    name: "dash flying forward yamcha r spirit ball",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 32,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 40,
  },
  {
    name: "dash flying caster yamcha r spirit ball return",
    repeatInterval: 1, 
    startTick: 33,
    endTick: -1,
    targetDirection: Dash.DIRECTION_CASTER_POINT,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 50,
  },
  // yamcha r wolf fang flash
  {
    name: "dash ground forward yamcha r wolf fang flash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 5,
  },
  // yamcha r homerun
  {
    name: "dash ground forward yamcha r homerun",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 6,
  },
  // yamcha r full power kame pushback
  {
    name: "dash ground forward yamcha r full power kame pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 30,
  },
  // roshi max power
  {
    name: "dash ground forward roshi max power",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // all might left smash
  {
    name: "dash ground forward all might left smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2.5,
  },
  // all might right smash
  {
    name: "dash ground forward all might right smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2,
  },
  // united states of smash
  {
    name: "dash ground point united states of smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 50,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 33,
  },
  // one for all
  {
    name: "dash ground forward one for all",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 1,
  },
  // oklahoma smash
  {
    name: "dash ground forward oklahoma smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // carolina smash
  {
    name: "dash ground point carolina smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  // california smash
  {
    name: "dash ground point california smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // new hampshire smash
  {
    name: "dash ground point new hampshire smash pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 30,
  },
  // mario jump
  {
    name: "dash ground forward mario jump",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2,
  },
  // mario spin jump
  {
    name: "dash ground forward spin jump",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2,
  },
  // mario power up block
  {
    name: "dash ground forward power up block",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 1,
  },
  // ichigo shunpo
  {
    name: "dash shunpo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    dashType: Dash.DASH_TYPE_ZANZO,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1400,
  },
  // ichigo hirenkyaku
  {
    name: "dash hirenkyaku",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 1100,
  },
  // dash bankai final on hit
  {
    name: "dash bankai final on hit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 31,
  },
  // dart speed boost
  {
    name: "dash ground forward dart speed boost",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 2.5,
  },
  // crush dance
  {
    name: "dash ground point crush dance",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  // blazing dynamo
  {
    name: "dash ground point blazing dynamo 1",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 270,
    distance: 20,
  },
  {
    name: "dash ground point blazing dynamo 2",
    repeatInterval: 1, 
    startTick: 13,
    endTick: 38,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 90,
    distance: 20,
  },
  {
    name: "dash ground point blazing dynamo 3",
    repeatInterval: 1, 
    startTick: 38,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 270,
    distance: 20,
  },
  // dash paragon of flame on hit
  {
    name: "dash paragon of flame on hit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 31,
  },
  // final burst
  {
    name: "dash ground point final burst",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 25,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  // ----------------------------
  // cell-x
  {
    name: "dash ground forward cell-x pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 4,
  },
  // nova chariot
  {
    name: "dash ground point nova chariot",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  // behind you
  {
    name: "dash ground point behind you pushback",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 10,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 180,
    distance: 35,
  },
  // saibaman bomb
  {
    name: "dash ground unit saibaman bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_UNIT_TARGET,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 37,
  },
  // power level sharing
  {
    name: "dash forward power level sharing",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // bunkai teleport dash
  {
    name: "dash ground point bunkai teleport",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 12,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 60,
  },
  // lightning shower rain
  {
    name: "dash flying forward lightning shower rain",
    repeatInterval: 1, 
    startTick: 50,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 55,
  },
  // belly armor
  {
    name: "dash ground forward belly armor",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 8,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // krown toss
  {
    name: "dash flying forward krown toss",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 50,
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 45,
  },
  {
    name: "dash flying caster krown toss return",
    repeatInterval: 1, 
    startTick: 51,
    endTick: -1,
    targetDirection: Dash.DIRECTION_CASTER_POINT,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 67,
  },
  // kharge
  {
    name: "dash ground point kharge",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 35,
  },
  // ginyu pose fighting
  {
    name: "dash ground forward ginyu pose fighting",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // nova strike
  {
    name: "dash ground point nova strike",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 20,
  },
  // emperors throne
  {
    name: "dash ground forward emperors throne",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 3,
  },
  // impaling rush
  {
    name: "dash ground point impaling rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // nova rush
  {
    name: "dash ground point nova rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 25,
  },
  // nova rush golden
  {
    name: "dash ground point nova rush golden",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 30,
  },
  // cage of light
  {
    name: "dash flying point cage of light",
    repeatInterval: 1, 
    startTick: 0,
    endTick: 33,
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_FLYING,
    checkPreviousCoord: false,
    useLastCastPoint: true,
    angleOffset: 0,
    distance: 66,
  },
  // shadow fist
  {
    name: "dash ground point shadow fist",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 15,
  },
  // dragonic rage
  {
    name: "dash ground forward dragonic rage",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 3,
  },
  // guldo time stop
  {
    name: "dash ground forward guldo time stop",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 12,
  },
  // guldo pose
  {
    name: "dash ground forward ginyu pose guldo",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 1,
  },
  // zamasu god slash
  {
    name: "dash ground forward zamasu god slash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2.5,
  },
  // zamasu energy blades
  {
    name: "dash ground forward zamasu energy blades",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // one winged angel
  {
    name: "dash ground forward one winged angel",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // ss3
  {
    name: "dash ground forward gotenks ss3",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
  // ---
  // saga zanzo
  {
    name: "dash ground point zanzo saga",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_TARGET_POINT,
    dashType: Dash.DASH_TYPE_ZANZO,
    checkPreviousCoord: false,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 32,
  },
  // saga max power
  {
    name: "dash ground forward max power saga",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,    
    targetDirection: Dash.DIRECTION_SOURCE_FORWARD,
    dashType: Dash.DASH_TYPE_GROUND,
    checkPreviousCoord: true,
    useLastCastPoint: false,
    angleOffset: 0,
    distance: 2,
  },
]