export const JumpComponents = [
  {
    name: "jump videl flying kick",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump saibaman bomb",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 22,
    maxHeight: 300,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump beam hand kannon",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 40,
    maxHeight: 700,
    useSpeedToCastPoint: true,
    speed: 40,
  },
  {
    name: "jump nova rush",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 25,
    maxHeight: 600,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump justice kick on hit",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 15,
    maxHeight: 400,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump yamcha r sledgehammer",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 13,
    maxHeight: 400,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump california smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 25,
    maxHeight: 700,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump hells gate sephiroth",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 25,
    maxHeight: 800,
    useSpeedToCastPoint: false,
    speed: -1,
  },
  {
    name: "jump new hampshire smash",
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    duration: 33,
    maxHeight: 300,
    useSpeedToCastPoint: false,
    speed: -1,
  },
]