import { MultiComponent } from "CustomAbility/AbilityComponent/MultiComponent";

export const MultiComponents = [
  {
    name: "multi twin dragon shot", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 30,
    angleMin: -15,
    angleMax: 15,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 16,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 2,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: false,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam twin dragon shot" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi final flash 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -2.5,
    angleMax: 2.5,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 2,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam final flash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi energy blast volley", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -20,
    angleMax: 20,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 21,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam energy blast volley" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super masenko", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -5,
    angleMax: 5,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 2,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam masenko" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi father-son kame", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 500,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam father-son kame" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi father-son kame goku", 
    repeatInterval: 1, 
    startTick: 99,
    endTick: -1,
    angleDifference: 1,
    angleMin: 170,
    angleMax: 171,
    forceMinDistance: 250,
    forceMaxDistance: 250,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "sfx father-son kame goku" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi hellzone grenade", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 30,
    angleMin: -60,
    angleMax: 300,
    forceMinDistance: 800,
    forceMaxDistance: 800,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 12,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: true,
    targetSource: MultiComponent.SOURCE_TARGET_UNIT,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam hellzone grenade" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi hellzone grenade 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 60,
    angleMin: 60,
    angleMax: -300,
    forceMinDistance: 500,
    forceMaxDistance: 500,
    delayBetweenComponents: 4,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 6,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: true,
    targetSource: MultiComponent.SOURCE_TARGET_UNIT,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam hellzone grenade" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi innocence breath", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -60,
    angleMax: 60,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 12,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam innocence breath" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi mankind destruction attack", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -179,
    angleMax: 180,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 2,
    // delayBetweenComponents: 1,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 132,
    // multiplyComponents: 264,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam mankind destruction attack" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi double sunday", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 8,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 2,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam double sunday" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi blazing storm", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -20,
    angleMax: 20,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi blazing storm 1", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 0,
    angleMin: -20,
    angleMax: -20,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  {
    name: "multi blazing storm 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 0,
    angleMin: -10,
    angleMax: -10,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  {
    name: "multi blazing storm 3", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 0,
    angleMin: 0,
    angleMax: 0,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  {
    name: "multi blazing storm 4", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 0,
    angleMin: 10,
    angleMax: 10,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  {
    name: "multi blazing storm 5", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 0,
    angleMin: 20,
    angleMax: 20,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target blazing storm explosion" },
      { name: "sfx blazing storm" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi lava burst", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 60,
    angleMin: -150,
    angleMax: 150,
    forceMinDistance: 600,
    forceMaxDistance: 600,
    delayBetweenComponents: 6,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: false,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam lava burst" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi lava pillars", 
    repeatInterval: 8, 
    startTick: 0,
    endTick: -1,
    angleDifference: 40,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 300,
    forceMaxDistance: 600,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target lava pillars" },
      { name: "sfx lava pillars" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi lava pillars 2", 
    repeatInterval: 8, 
    startTick: 0,
    endTick: -1,
    angleDifference: 40,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 600,
    forceMaxDistance: 1000,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage target lava pillars" },
      { name: "sfx lava pillars" },
    ],
  },
  // -------------------------------------------
  // {
  //   name: "multi barrier prison", 
  //   repeatInterval: 1, 
  //   startTick: 0,
  //   endTick: -1,
  //   angleDifference: 0,
  //   angleMin: 0,
  //   angleMax: 0,
  //   forceMinDistance: 0,
  //   forceMaxDistance: 0,
  //   delayBetweenComponents: 0,
  //   firingMode: MultiComponent.SPREAD_FIRING,
  //   multiplyComponents: 1,
  //   componentsAddedPerRound: 1,
  //   alwaysUpdateAngle: false,
  //   fixedSourceCoords: true,
  //   targetSource: MultiComponent.SOURCE_TARGET_UNIT,
  //   useLastCastPoint: true,
  //   sfxList: true,
  //   components: [
  //     { name: "beam barrier prison" },
  //   ],
  // },
  // -------------------------------------------
  {
    name: "multi barrier wall", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 15,
    angleMin: -60,
    angleMax: 60,
    forceMinDistance: 500,
    forceMaxDistance: 0,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 8,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam barrier wall" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super electric strike", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -60,
    angleMax: 60,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 12,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super electric strike" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi power blitz barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -2,
    angleMax: 2,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 16,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 10,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam power blitz barrage" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi videl punch", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 225,
    forceMaxDistance: 225,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 3,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage videl punch" },
      { name: "knockback videl punch" },
      { name: "sfx videl punch" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi brave slash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 3,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage brave slash" },
      { name: "debuff brave slash feedback" },
      { name: "sfx brave slash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi heatwave", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -25,
    angleMax: 25,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam heatwave" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi heatwave 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -25,
    angleMax: 25,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam heatwave 2" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi justice flash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 8,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 8,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam justice flash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi justice flash 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 8,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 12,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam justice flash 2" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi detroit smash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage detroit smash" },
      { name: "sfx detroit smash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi all might left smash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "damage all might left smash" },
      { name: "sfx all might left smash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi all might right smash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "damage all might right smash" },
      { name: "sfx all might right smash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi one for all 1", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 6,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 150,
    forceMaxDistance: 150,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam one for all 1" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi one for all 2", 
    repeatInterval: 1, 
    startTick: 12,
    endTick: -1,
    angleDifference: 6,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 150,
    forceMaxDistance: 150,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam one for all 2" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi one for all 3", 
    repeatInterval: 1, 
    startTick: 24,
    endTick: -1,
    angleDifference: 6,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 150,
    forceMaxDistance: 150,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam one for all 3" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi one for all 4", 
    repeatInterval: 1, 
    startTick: 36,
    endTick: -1,
    angleDifference: 6,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 150,
    forceMaxDistance: 150,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam one for all 4" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi one for all 5", 
    repeatInterval: 1, 
    startTick: 48,
    endTick: -1,
    angleDifference: 6,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 150,
    forceMaxDistance: 150,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam one for all 5" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi solar kame", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 500,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam solar kame" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi devil claw", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -10,
    angleMax: 10,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 3,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam devil claw" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi lightning shower rain", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 20,
    angleMin: -50,
    angleMax: 50,
    forceMinDistance: 350,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 6,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam lightning shower rain" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi hand kannon", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam hand kannon" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi blast-o-matic", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 500,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam blast-o-matic" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi frost claws", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 15,
    angleMin: -22,
    angleMax: 24,
    forceMinDistance: 200,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 4,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam frost claws" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi galaxy dynamite", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 10,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 4,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam galaxy dynamite" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi death beam barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -10,
    angleMax: 10,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 5,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam death beam barrage" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi death saucer", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 30,
    angleMin: -15,
    angleMax: 15,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 16,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: false,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam death saucer 1" },
      { name: "beam death saucer 2" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi cage of light", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 30,
    angleMin: -60,
    angleMax: 300,
    forceMinDistance: 550,
    forceMaxDistance: 550,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 12,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: true,
    targetSource: MultiComponent.SOURCE_TARGET_POINT,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam cage of light pillar" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi dragoon flourish", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 225,
    forceMaxDistance: 225,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage dragoon flourish explosion" },
      { name: "sfx dragoon flourish" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi dragon flash bullet", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -20,
    angleMax: 20,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 21,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam dragon flash bullet" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi nova star omega", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 500,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam nova star" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi scattering bullet start 1", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 90,
    angleMin: -6,
    angleMax: 354,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam scattering bullet start 1" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi scattering bullet start 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 45,
    angleMin: 6,
    angleMax: 366,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam scattering bullet start 2" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r wolf fang volley", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -20,
    angleMax: 20,
    forceMinDistance: 50,
    forceMaxDistance: 50,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 16,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam yamcha r wolf fang volley" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r reverse wolf fang blast", 
    repeatInterval: 1, 
    startTick: 4,
    endTick: -1,
    angleDifference: 1,
    angleMin: 179,
    angleMax: 180,
    forceMinDistance: 100,
    forceMaxDistance: 100,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 3,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "beam yamcha r wolf fang blast" },
      { name: "sfx yamcha r wolf fang blast" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r neo wolf fang blast", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 100,
    forceMaxDistance: 100,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "beam yamcha r neo wolf fang blast" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r flash kame", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 250,
    forceMaxDistance: 250,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "beam yamcha r flash kame" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r wolf fang barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 40,
    angleMin: -60,
    angleMax: 60,
    forceMinDistance: 50,
    forceMaxDistance: 50,
    delayBetweenComponents: 2,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 4,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam yamcha r wolf fang barrage" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r yamcha blast", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 250,
    forceMaxDistance: 250,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "beam yamcha r yamcha blast" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi yamcha r wolf fang pitching fist", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 250,
    forceMaxDistance: 250,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_SOURCE_FORWARD,
    sfxList: true,
    components: [
      { name: "beam yamcha r wolf fang pitching fist" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi psychic rock throw", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 11,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 2,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam psychic rock throw" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi divine authority", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -1,
    angleMax: 1,
    forceMinDistance: 200,
    forceMaxDistance: 200,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam divine authority" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi octoslash", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 5,
    angleMin: -5,
    angleMax: 5,
    forceMinDistance: 325,
    forceMaxDistance: 325,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 2,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage octoslash" },
      { name: "sfx octoslash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi hammer time", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 225,
    forceMaxDistance: 225,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 3,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "damage hammer time" },
      { name: "debuff slow flatten" },
      { name: "sfx hammer time" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super cape", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 225,
    forceMaxDistance: 225,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "knockback super cape" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi goten rock throw", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -4,
    angleMax: 4,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 7,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 6,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam goten rock throw" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi die die missile barrage", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 12,
    angleMin: -60,
    angleMax: 60,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 5,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 10,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam die die missile barrage" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super ghost kamikaze attack", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 36,
    angleMin: -90,
    angleMax: 90,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 10,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 5,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super ghost kamikaze attack" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super ghost kamikaze attack 2", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 36,
    angleMin: -90,
    angleMax: 90,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 10,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 10,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super ghost kamikaze attack" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super saiyan 3 ghosts 1", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 120,
    forceMaxDistance: 120,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super ghost kamikaze attack orbit" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super saiyan 3 ghosts 2", 
    repeatInterval: 1, 
    startTick: 12,
    endTick: -1,
    angleDifference: 10,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 120,
    forceMaxDistance: 120,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super ghost kamikaze attack orbit" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi super saiyan 3 ghosts 3", 
    repeatInterval: 1, 
    startTick: 24,
    endTick: -1,
    angleDifference: 10,
    angleMin: 0,
    angleMax: 360,
    forceMinDistance: 120,
    forceMaxDistance: 120,
    delayBetweenComponents: 1,
    firingMode: MultiComponent.WRAPAROUND_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: true,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam super ghost kamikaze attack orbit" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi burning rush", 
    repeatInterval: 1, 
    startTick: 20,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 300,
    forceMaxDistance: 300,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: false,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam burning rush" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi madness slash", 
    repeatInterval: 1, 
    startTick: 20,
    endTick: -1,
    angleDifference: 1,
    angleMin: 0,
    angleMax: 1,
    forceMinDistance: 300,
    forceMaxDistance: 300,
    delayBetweenComponents: 0,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 1,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: true,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: false,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam madness slash" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi power blitz barrage saga", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 1,
    angleMin: -2,
    angleMax: 2,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 16,
    firingMode: MultiComponent.SPREAD_FIRING,
    multiplyComponents: 14,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam power blitz barrage saga" },
    ],
  },
  // -------------------------------------------
  {
    name: "multi mankind destruction attack saga", 
    repeatInterval: 1, 
    startTick: 0,
    endTick: -1,
    angleDifference: 10,
    angleMin: -179,
    angleMax: 180,
    forceMinDistance: 0,
    forceMaxDistance: 0,
    delayBetweenComponents: 6,
    firingMode: MultiComponent.RANDOM_FIRING,
    multiplyComponents: 22,
    componentsAddedPerRound: 1,
    alwaysUpdateAngle: false,
    fixedSourceCoords: false,
    fixedReplacementCoords: false,
    targetSource: MultiComponent.SOURCE_CASTER,
    useLastCastPoint: true,
    whichTargetPoint: MultiComponent.TARGET_POINT_TARGET,
    sfxList: true,
    components: [
      { name: "beam mankind destruction attack" },
    ],
  },
];