import { SfxComponent } from "CustomAbility/AbilityComponent/SfxComponent";

export const SfxComponents = [
  // copy from here
  { 
    name: "sfx zanzo dash", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.1,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      // note: attached sfx cant alter scale, height, yaw, 
      // only repeat, color, persistent, attachment for now
      {
        model: "DustWindFasterExact.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // to here, and replace with unique name
  { 
    name: "sfx max power", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 0,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "DustWave.mdl",
        repeatInterval: 33,
        group: 0,
        scale: 0.75,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam kamehameha", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 1.2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "IceNova.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Human\\Feedback\\SpellBreakerAttack.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam god kamehameha", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 1.3,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\AbsorbMana\\AbsorbManaBirthMissile.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 3,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "IceNova.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\ReplenishMana\\ReplenishManaCasterOverhead.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 3,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Human\\Feedback\\SpellBreakerAttack.mdl",
        repeatInterval: 6,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam spirit bomb", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Orc\\Purge\\PurgeBuffTarget.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 2,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\SpellShieldAmulet\\SpellShieldCaster.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 1.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\TomeOfRetraining\\TomeOfRetrainingCaster.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 25,
          y: 105,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "BlueBigExplosion.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Other\\Drain\\ManaDrainCaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx dragon fist", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DarkPortal\\DarkPortalTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\SearingArrow\\SearingArrowMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
      {
        model: "units\\human\\phoenix\\phoenix.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "overhead",
      },
      {
        model: "units\\creeps\\BronzeDragon\\BronzeDragon.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam galick gun", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "CalamityParticle3.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\AIre\\AIreTarget.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 3,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [],
  },
  // --------------------------------------------
  { 
    name: "sfx beam big bang attack", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Orc\\Purge\\PurgeBuffTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 3,
        startHeight: 200,
        endHeight: 200,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Firaga.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Human\\ManaFlare\\ManaFlareMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam final flash", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Human\\Invisibility\\InvisibilityTarget.mdl",
        repeatInterval: 3,
        group: 0,
        scale: 2.5,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 175,
          z: 105,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Des.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 3,
        startHeight: 150,
        endHeight: 150,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\ReplenishHealth\\ReplenishHealthCaster.mdl",
        repeatInterval: 8,
        group: 0,
        scale: 3,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NewDirtEXNofire.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Undead\\CarrionSwarm\\CarrionSwarmMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam energy blast volley", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [

    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Undead\\CarrionSwarm\\CarrionSwarmMissile.mdl",
        repeatInterval: 10,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam masenko", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Des.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2.5,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 175,
          z: 105,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\AIhe\\AIheTarget.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 2.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NewDirtEXNofire.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx super dragon flight", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraSS.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\SearingArrow\\SearingArrowMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam finish buster", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 215,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [],
  },
  // --------------------------------------------
  { 
    name: "sfx beam heat dome attack", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 215,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Firaga.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 215,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx burning attack", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_TARGET_POINT,
    sfxList: [
      {
        model: "NewDirtEXNofire.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "LightStrikeArray2.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Impact.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx blazing rush", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DarkPortal\\DarkPortalTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2.0,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NewDirtEXNofire.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.1,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\SearingArrow\\SearingArrowMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx super saiyan rage", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl",
        repeatInterval: 19,
        group: 0,
        scale: 0.6,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraLightBlue.mdl",
        repeatInterval: 19,
        group: 0,
        scale: 0.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam special beam cannon", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "BeamCannonHead.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2.5,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 175,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\DarkRitual\\DarkRitualTarget.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 0.75,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 175,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "BeamCannonHead.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 175,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx future sight", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "BlackBlink.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageCaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx tyrant lancer", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 25,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraSS.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam tyrant lancer", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Des.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NewDirtEXNofire.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx saiyan spirit", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 22,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraBlue.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam saiyan spirit", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "IceNova.mdl",
        repeatInterval: 30,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Firaga.mdl",
        repeatInterval: 30,
        group: 0,
        scale: 2.2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam riot javelin", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 0.3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 105,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\TomeOfRetraining\\TomeOfRetrainingCaster.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 25,
          y: 105,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "BlueBigExplosion.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx rebellion spear", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 125,
          y: 125,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraLightBlue.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx angry shout", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 33,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 234,
          y: 202,
          z: 218,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl",
        repeatInterval: 33,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam energy beam", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Undead\\Cripple\\CrippleTarget.mdl",
        repeatInterval: 3,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 12,
        group: 0,
        scale: 1.2,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx nuke", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_TARGET_POINT,
    sfxList: [
      {
        model: "NuclearExplosion.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.71,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx ss deadly hammer", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 25,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "DustWindFasterExact.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 0.4,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam ss deadly bomber", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl",
        repeatInterval: 8,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "SSDB.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx overcharge", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.5,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 125,
          z: 105,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx haretsu", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_TARGET_POINT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Demon\\DemonBoltImpact\\DemonBoltImpact.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 1.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 105,
          z: 105,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx innocence breath", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Environment\\LargeBuildingFire\\LargeBuildingFire2.mdl",
        repeatInterval: 3,
        group: 0,
        scale: 1.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx angry explosion delay", 
    repeatInterval: 1,
    startTick: 0,
    endTick: 50,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Orc\\Voodoo\\VoodooAura.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx angry explosion explosion", 
    repeatInterval: 1,
    startTick: 50,
    endTick: 50,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "NewMassiveEX.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NuclearExplosion.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 1.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam vanishing ball", 
    repeatInterval: 1,
    startTick: 16,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 5.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam mankind destruction attack", 
    repeatInterval: 1,
    startTick: 16,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl",
        repeatInterval: 6,
        group: 0,
        scale: 5.0,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 225,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Items\\AIre\\AIreTarget.mdl",
        repeatInterval: 20,
        group: 0,
        scale: 1.5,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\OrbOfDeath\\AnnihilationMissile.mdl",
        repeatInterval: 17,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx energy punch", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "AuraDarkGreen.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
      {
        model: "Abilities\\Spells\\Other\\AcidBomb\\BottleImpact.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx power level rising", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "AuraDarkGreen.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.5,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.5,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam planet crusher", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 3,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\DarkSummoning\\DarkSummonMissile.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 3,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\Unsummon\\UnsummonTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 2.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 3.2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\NightElf\\Tranquility\\TranquilityTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [

    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam gigantic roar", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Human\\Banish\\BanishTarget.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\NightElf\\Immolation\\ImmolationTarget.mdl",
        repeatInterval: 3,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl",
        repeatInterval: 3,
        group: 0,
        scale: 2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 205,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\NightElf\\Immolation\\ImmolationTarget.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 255,
          z: 205,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam gigantic omegastorm", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Undead\\Darksummoning\\DarkSummonTarget.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 3,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 2.5,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\DeathCoil\\DeathCoilSpecialArt.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 255,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [

    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam death beam frieza", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "DeathBeamHead.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Human\\SpellSteal\\SpellStealMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 3,
        startHeight: 100,
        endHeight: 100,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam supernova cooler", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DemonBoltImpact\\DemonBoltImpact.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 2,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DarkPortal\\DarkPortalTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 205,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 155,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx nova chariot", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Items\\OrbCorruption\\OrbCorruptionMissile.mdl",
        repeatInterval: 1,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Undead\\OrbOfDeath\\AnnihilationMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam deafening wave", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 7,
        group: 0,
        scale: 1.2,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "DustWindFasterExact.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 0.5,
        startHeight: 25,
        endHeight: 25,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam supernova golden", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 16,
        group: 0,
        scale: 1.3,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DemonBoltImpact\\DemonBoltImpact.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 2,
        startHeight: 50,
        endHeight: 50,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 105,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Demon\\DarkPortal\\DarkPortalTarget.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 4,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NuclearExplosion.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 225,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "BeerBall.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx blue hurricane", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 25,
        group: 0,
        scale: 1.1,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Other\\Tornado\\TornadoElemental.mdl",
        repeatInterval: 75,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
      {
        model: "Objects\\Spawnmodels\\Naga\\NagaDeath\\NagaDeath.mdl",
        repeatInterval: 50,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 55,
          y: 105,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam blue", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Undead\\FrostNova\\FrostNovaTarget.mdl",
        repeatInterval: 8,
        group: 0,
        scale: 1.2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Undead\\ReplenishMana\\ReplenishManaCasterOverhead.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 205,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam purple", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Spells\\Undead\\OrbOfDeath\\AnnihilationMissile.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 1.2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 1.2,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\Spells\Orc\Purge\PurgeBuffTarget.mdl",
        repeatInterval: 5,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 105,
          y: 155,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "overhead",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx beam red", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "Abilities\\Weapons\\VengeanceMissile\\VengeanceMissile.mdl",
        repeatInterval: 2,
        group: 0,
        scale: 1.3,
        startHeight: 75,
        endHeight: 75,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Volcano\\VolcanoMissile.mdl",
        repeatInterval: 4,
        group: 0,
        scale: 0.6,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "NuclearExplosion.mdl",
        repeatInterval: -1,
        group: 0,
        scale: 0.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 155,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile_mini.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
      {
        model: "Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 205,
          z: 55,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx blue wind aura", 
    repeatInterval: 0,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "WindCircleFaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.5,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 155,
          y: 205,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      // {
      //   model: "Abilities\\Spells\\NightElf\\Starfall\\StarfallCaster.mdl",
      //   repeatInterval: 0,
      //   group: 0,
      //   scale: 1.5,
      //   startHeight: 0,
      //   endHeight: 0,
      //   extraDirectionalYaw: 0,
      //   color: {
      //     x: 155,
      //     y: 205,
      //     z: 255,
      //   },
      //   persistent: true,
      //   attachmentPoint: "origin",
      // },
    ],
  },
  // --------------------------------------------
  { 
    name: "sfx ultra instinct", 
    repeatInterval: 1,
    startTick: 0,
    endTick: -1,
    sfxSource: SfxComponent.SOURCE_UNIT,
    sfxList: [
      {
        model: "BlackBlink.mdl",
        repeatInterval: 7,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
      {
        model: "Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageCaster.mdl",
        repeatInterval: 10,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: false,
        attachmentPoint: "",
      },
    ],
    attachedSfxList: [
      {
        model: "Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageCaster.mdl",
        repeatInterval: 0,
        group: 0,
        scale: 1.0,
        startHeight: 0,
        endHeight: 0,
        extraDirectionalYaw: 0,
        color: {
          x: 255,
          y: 255,
          z: 255,
        },
        persistent: true,
        attachmentPoint: "origin",
      },
    ],
  },
  // --------------------------------------------
];