import { Id } from "Common/Constants";
import { AbilityNames } from "CustomAbility/AbilityNames";


export const DualTechPartList = [
  {
    name: "goku black sorrowful scythe",
    reqUnitTypeId: 0,
    reqAbilityId: Id.gokuBlackSorrowfulScythe,
    forceCastAbilityName: "",
    castNothing: false,
    showForceCastText: false,
    useReqAbilityLevel: false,
    includeAllies: false,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "frog x strike",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogSlurpCut,
    forceCastAbilityName: AbilityNames.Crono.X_STRIKE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono x strike",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoSlash,
    forceCastAbilityName: AbilityNames.Crono.X_STRIKE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "robo rocket roll",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboLaserSpin,
    forceCastAbilityName: AbilityNames.Robo.ROCKET_ROLL,
    castNothing: false,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: true,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "robo super volt",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboElectrocute,
    forceCastAbilityName: AbilityNames.Robo.SUPER_VOLT,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono super volt",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoLightning2,
    forceCastAbilityName: AbilityNames.Crono.SUPER_VOLT,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono aura whirl",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCyclone,
    forceCastAbilityName: AbilityNames.Crono.AURA_WHIRL,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "marle aura whirl",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleAura,
    forceCastAbilityName: AbilityNames.Crono.AURA_WHIRL,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "ayla drill kick",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaTailSpin,
    forceCastAbilityName: AbilityNames.Ayla.DRILL_KICK,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "ayla volt bite",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaCharm,
    forceCastAbilityName: AbilityNames.Ayla.VOLT_BITE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono ice sword",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCleave,
    forceCastAbilityName: AbilityNames.Crono.ICE_SWORD,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "lucca antipode 1",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "marle antipode 1",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleIce,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "lucca antipode 2",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "marle antipode 2",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleIce2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "frog ice water",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogWater,
    forceCastAbilityName: AbilityNames.Frog.ICE_WATER,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "frog glacier",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogWater2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "marle glacier",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleIce2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "ayla ice toss",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaBoulderToss,
    forceCastAbilityName: AbilityNames.Ayla.ICE_TOSS,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "ayla cube toss",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaBoulderToss,
    forceCastAbilityName: AbilityNames.Ayla.CUBE_TOSS,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "robo aura beam",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboHealBeam,
    forceCastAbilityName: AbilityNames.Marle.AURA_BEAM,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "marle aura beam",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleAura,
    forceCastAbilityName: AbilityNames.Marle.AURA_BEAM,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "robo ice tackle",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboTackle,
    forceCastAbilityName: AbilityNames.Robo.ICE_TACKLE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono flame whirl",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCyclone,
    forceCastAbilityName: AbilityNames.Crono.FLAME_WHIRL,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono fire sword",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCleave,
    forceCastAbilityName: AbilityNames.Crono.FIRE_SWORD,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "marle antipode 3",
    reqUnitTypeId: 0,
    reqAbilityId: Id.marleIce2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 15,
  },
  {
    name: "frog red pin",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogAerialStrike,
    forceCastAbilityName: AbilityNames.Frog.RED_PIN,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "frog line bomb",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogAerialStrike,
    forceCastAbilityName: AbilityNames.Frog.LINE_BOMB,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "robo fire tackle",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboTackle,
    forceCastAbilityName: AbilityNames.Robo.FIRE_TACKLE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "ayla fire whirl",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaTailSpin,
    forceCastAbilityName: AbilityNames.Ayla.FIRE_WHIRL,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono sword stream",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCleave,
    forceCastAbilityName: AbilityNames.Crono.SWORD_STREAM,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono spire 2",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoLightning2,
    forceCastAbilityName: AbilityNames.Crono.SPIRE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: true,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono spire 3",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoLightning3,
    forceCastAbilityName: AbilityNames.Crono.SPIRE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: true,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "robo blade toss",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboLaserSpin,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "robo bubble snap",
    reqUnitTypeId: 0,
    reqAbilityId: Id.roboTackle,
    forceCastAbilityName: AbilityNames.Robo.BUBBLE_SNAP,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "ayla bubble hit",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaTripleKick,
    forceCastAbilityName: AbilityNames.Ayla.BUBBLE_HIT,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "crono max cyclone",
    reqUnitTypeId: 0,
    reqAbilityId: Id.cronoCyclone,
    forceCastAbilityName: AbilityNames.Crono.MAX_CYCLONE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: true,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "lucca fire uzzi punch 1",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "lucca fire uzzi punch 2",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "ayla boogie",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaCharm,
    forceCastAbilityName: AbilityNames.Robo.BOOGIE,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
  {
    name: "ayla spin kick",
    reqUnitTypeId: 0,
    reqAbilityId: Id.aylaTripleKick,
    forceCastAbilityName: AbilityNames.Ayla.SPIN_KICK,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "lucca blaze kick 1",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "lucca blaze kick 2",
    reqUnitTypeId: 0,
    reqAbilityId: Id.luccaFire2,
    forceCastAbilityName: "",
    castNothing: true,
    showForceCastText: false,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 3,
  },
  {
    name: "frog slurp kiss",
    reqUnitTypeId: 0,
    reqAbilityId: Id.frogSlurp,
    forceCastAbilityName: AbilityNames.Frog.SLURP_KISS,
    castNothing: false,
    showForceCastText: true,
    useReqAbilityLevel: true,
    includeAllies: true,
    setTargetUnitToSrcCaster: false,
    applyCd: true,
    applyOriginalCd: true,
    cdPenalty: 0,
  },
];